### ISSUE TITLE
Typo in quizzes/quiz1.rs

### ISSUE THREAD

**Issue by yadokani389** [sotanengel/rustlings-jp#3]
exercises/quizzes/quiz1.rsの8行目、りんご1個の値段は1 rustbucks ではないでしょうか。

**Comment by sotanengel** [comment]
@yadokani389 
コメントありがとうございます！
こちら原文では以下のようになっているため、翻訳ミスです。。。
https://github.com/rust-lang/rustlings/blob/0c79f2ea3e1fd2db54ebe8fba8ed17369a15b365/exercises/quizzes/quiz1.rs#L6-L9

以下のコミットで日本語の説明を修正しておきました。
https://github.com/sotanengel/rustlings-jp/commit/a0a37846501429c9a90855984303b425776aa190
