### ISSUE TITLE
Typo in 13_error_handling/errors6.rs

### ISSUE THREAD

**Issue by Nakanishi123** [sotanengel/rustlings-jp#4]
カウタム -> カスタム

https://github.com/sotanengel/rustlings-jp/blob/189cce17ef268e9b18fb8fc3033da2801475bcb5/solutions/13_error_handling/errors6.rs#L13

https://github.com/sotanengel/rustlings-jp/blob/189cce17ef268e9b18fb8fc3033da2801475bcb5/exercises/13_error_handling/errors6.rs#L13

**Comment by sotanengel** [comment]
@Nakanishi123 
ご指摘ありがとうございます！
以下のコミットで修正を反映してきました。
https://github.com/sotanengel/rustlings-jp/commit/370db6a490b15ea1bb6066f557ab80f0dac5cea8#diff-11290c0cd495f440946a238d4418b3014f5b40d35d5122da0f2730b10cfab849L13
