### ISSUE TITLE
 Typo in 18_iterators/iterators4.rs

### ISSUE THREAD

**Issue by Nakanishi123** [sotanengel/rustlings-jp#5]
朝鮮問題 -> 挑戦問題

https://github.com/sotanengel/rustlings-jp/blob/a0a37846501429c9a90855984303b425776aa190/exercises/18_iterators/iterators4.rs#L11

**Comment by mitkeicat** [comment]
Rustlingsの日本語版サードパーティー　について、２，Rustのインストールできました。３，演習問題のダウンロードできました。４．の演習問題にチャレンジを、パワーシェルでrustlings 起動すると、起動してエンターを押すと、画面が流れて止まらななくなります。　なにか設定が必要でしょうか？　　よろしくおねがいします

**Comment by sotanengel** [comment]
@Nakanishi123 確認遅れました。
報告ありがとうございます！
以下で、修正しました🙇

https://github.com/sotanengel/rustlings-jp/commit/00f1729361a2f58acfcd932b9580169d644ec388
